### ISSUE TITLE
Add slf4j-simple to test class paths

### ISSUE THREAD

**Issue by fschopp** [cloudkeeper-project/cloudkeeper#16]
A few tests output the following error message

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

These projects need `slf4j-simple` on the test classpath, which should thus be added to the Maven pom.

**Comment by priimak** [comment]
FYI. This message appears only in cloudkeeper-executors/cloudkeeper-forking-executor/
