### ISSUE TITLE
Cloudkeeper requiring qemu-img version >= 2 is a problem under SL7

### ISSUE THREAD

**Issue by StephaneGerardVUB** [cloudkeeper-project/cloudkeeper#35]
Hi, I've tried to install centos-release-qemu-ev on my opennebula frontend that is running under SL7.2, but it doesn't work because this package requires centos-release-virt-common that in turn requires centos-release. Cheers, Stéphane

**Comment by fschopp** [comment]
I assume you meant to post this issue somewhere else?

**Comment by StephaneGerardVUB** [comment]
Oups, you're right, apologize.

**Comment by fschopp** [comment]
No problem.
